CREATE TABLE `restaurant_dishes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`restaurantId` int NOT NULL,
	`name` varchar(256) NOT NULL,
	`description` text,
	`estimatedKcal` float,
	`proteinG` float,
	`carbG` float,
	`fatG` float,
	`sodiumMg` float,
	`healthFlags` json DEFAULT ('[]'),
	`iconUrl` varchar(512),
	`imageUrl` varchar(512),
	`imageStatus` enum('pending','generated','approved','rejected') DEFAULT 'pending',
	`foodDbId` varchar(64),
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `restaurant_dishes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `restaurants` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(128) NOT NULL,
	`name` varchar(256) NOT NULL,
	`shortName` varchar(64),
	`description` text,
	`culturalNote` text,
	`operatingSince` varchar(32),
	`tier` enum('hawker-legend','premium-local','fine-dining','chain','mamak','kopitiam') NOT NULL DEFAULT 'hawker-legend',
	`awards` json DEFAULT ('[]'),
	`region` enum('singapore','penang','kl','malacca','johor','malaysia') NOT NULL DEFAULT 'singapore',
	`area` varchar(256),
	`ethnic` json DEFAULT ('[]'),
	`occasions` json DEFAULT ('[]'),
	`dietary` json DEFAULT ('[]'),
	`website` varchar(512),
	`michelinNote` text,
	`coverImageUrl` varchar(512),
	`iconUrl` varchar(512),
	`status` enum('pending','approved','rejected','draft') NOT NULL DEFAULT 'pending',
	`submittedBy` int,
	`reviewedBy` int,
	`reviewNote` text,
	`submittedAt` timestamp DEFAULT (now()),
	`reviewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `restaurants_id` PRIMARY KEY(`id`),
	CONSTRAINT `restaurants_slug_unique` UNIQUE(`slug`)
);
